### ISSUE TITLE
Table (index) and forms (create/edit) error if using different relationship name

### ISSUE THREAD

**Issue by jay2success** [TiagoSilvaPereira/vemto-filament-plugin#3]
Hi,

Thanks for amazing plugin.

I found issue when testing this plugin.

Example there are User and BlogPost models.

User has many BlogPost.
BlogPost: user_id belongsTo User, with relationship name: user()

The problem is if i use different foreign key and relationship name, example:
BlogPost: author_id belongsTo User, with relationship name: author()

When building the BlogPostResource for filament:
1. on form fn()
`BelongToSelect()->relationship('user', 'name')`
should be:
`BelongToSelect()->relationship('author', 'name')`

2. on table fn()
`Tables\Columns\TextColumn::make('user.name')->limit(50),`
should be:
`Tables\Columns\TextColumn::make('author.name')->limit(50),`

and 

` MultiSelectFilter::make('author_id')->relationship(
                    'user',
                    'name'
                ),
`
should be
` MultiSelectFilter::make('author_id')->relationship(
                    'author',
                    'name'
                ),
`

Thanks.

**Comment by TiagoSilvaPereira** [comment]
Hi @jay2success thank you for reporting... tagging @nicollassilva

**Comment by nicollassilva** [comment]
Hi @jay2success , this issue has been fixed for the next version of the plugin coming out soon. Thank you.

**Comment by TiagoSilvaPereira** [comment]
Added to latest version

**Comment by jay2success** [comment]
Awesome, thanks for the support.
