### ISSUE TITLE
Suggestion: wrap the form with card to make it looks nicer like the demo

### ISSUE THREAD

**Issue by jay2success** [TiagoSilvaPereira/vemto-filament-plugin#5]
Hi,

This is not an issue, just suggestion.
The suggestion is to wrap all the form with Card so it will looks better, just like filament demo.
The current form has no card/background so visually looks confusing.

Current form:
`
return $form->schema([
                    Grid::make()->schema([
`

Suggestion:
`
return $form->schema([
            Forms\Components\Card::make()
                ->schema([
                    Grid::make()->schema([
`

Hope you will accept this.
Thanks again for this awesome plugin.

**Comment by TiagoSilvaPereira** [comment]
@jay2success thank you for your suggestion

**Comment by TiagoSilvaPereira** [comment]
Added to the latest version

**Comment by jay2success** [comment]
Awesome, thanks for the support.
