### ISSUE TITLE
This no longer work

### ISSUE THREAD

**Issue by ziming** [TiagoSilvaPereira/vemto-filament-plugin#6]
No Filament Resource generated

**Comment by TiagoSilvaPereira** [comment]
@ziming Hi, we tried it here and it worked well, could you please give more details? Screenshots, videos, etc.

**Comment by ziming** [comment]
are u on windows? I'm on a macbook

the last time it worked for me is pre vite

**Comment by TiagoSilvaPereira** [comment]
@ziming could you please try again creating a new project from zero and adding the Filament plugin (if possible please record the process through screenshots or video)... Vite has no relation with the Filament resources so that it may be another issue

**Comment by TiagoSilvaPereira** [comment]
Could you share your project .vemto file? So we can try it here

**Comment by ziming** [comment]
hmm but how could I move my models in the older project over? it's a lot of tables and columns and I dont want to recreate then all in the new vemto project

**Comment by TiagoSilvaPereira** [comment]
@ziming is there anything inside the folder ```app/Filament/Resources```?

**Comment by TiagoSilvaPereira** [comment]
I'm pinging @nicollassilva to help with that too

**Comment by ziming** [comment]
I think I dont even see the filament folder. but the plugin is installed in that project

I'm not on my laptop now. on my phone

**Comment by nicollassilva** [comment]
Hi @ziming , could you please check if the app/Filament folder has been installed?

**Comment by ziming** [comment]
Filament folder is not generated at all

**Comment by nicollassilva** [comment]
Hi @ziming, could you share your project .vemto file so I can check?

**Comment by ziming** [comment]
will try when I'm free as I'm going to sleep now (2+ am)

there r some sensitive data revealed by project name, folder paths.etc so I wonder if it is possible to edit the vemto project file to remove them 1st.

**Comment by TiagoSilvaPereira** [comment]
@ziming before sending your project, you may try creating a new simple project with Vemto and check if the issue happens (if true, you can just send this simple project instead of your whole project)

**Comment by ziming** [comment]
hi. creating a new project works
