### ISSUE TITLE
Use ->required() instead of ->rules(['required'])

### ISSUE THREAD

**Issue by ziming** [TiagoSilvaPereira/vemto-filament-plugin#9]
Currently this plugin use ->rules(['required'])

It is not the same as ->required(), when you use ->required(), filament also adds a red * beside the label.

**Comment by TiagoSilvaPereira** [comment]
Tagging @nicollassilva

**Comment by nicollassilva** [comment]
Hi @ziming, the new version of this plugin will fix this. Thank you!
